feat: add Arch package build

diff --git a/script/bundle-linux b/script/bundle-linux
--- a/script/bundle-linux
+++ b/script/bundle-linux
@@ -8,17 +8,18 @@ help_info() {
 Usage: ${0##*/} [options]
 Build Linux packages for Gram.
 
-At least one of --tarball, --deb, or --rpm must be specified.
+At least one of --tarball, --deb, --AppImage, --arch or --rpm must be specified.
 
 Options:
-  -h, --help          Display this help and exit.
-  --no-build          Skip building binaries (assume they're already built).
+  -h, --help          Display this help and exit
+  --no-build          Skip building binaries (assume they're already built)
   --no-build-remote   Skip building the remote_server binary
-  --flatpak           Set GRAM_BUNDLE_TYPE=flatpak so that this can be included in system info.
-  --tarball           Build a release .tar.gz archive.
-  --deb               Build a .deb package.
-  --rpm               Build a .rpm package.
-  --appimage          Build an AppImage.
+  --flatpak           Set GRAM_BUNDLE_TYPE=flatpak so that this can be included in system info
+  --tarball           Build a release .tar.gz archive
+  --deb               Build a .deb package
+  --rpm               Build a .rpm package
+  --arch              Build an Arch package
+  --appimage          Build an AppImage
   "
 }
 
@@ -28,6 +29,7 @@ DO_TARBALL=false
 DO_DEB=false
 DO_APPIMAGE=false
 DO_RPM=false
+DO_ARCH=false
 
 while [[ $# -gt 0 ]]; do
     case $1 in
@@ -65,6 +67,10 @@ while [[ $# -gt 0 ]]; do
         DO_RPM=true
         shift
         ;;
+    --arch)
+        DO_ARCH=true
+        shift
+        ;;
     --)
         shift
         break
@@ -83,8 +89,8 @@ while [[ $# -gt 0 ]]; do
 done
 
 # Throw error if no arguments given
-if [[ "$DO_TARBALL" == "false" && "$DO_DEB" == "false" && "$DO_RPM" == "false" && "$DO_APPIMAGE" == "false" ]]; then
-    echo "Error: At least one of --tarball, --deb, --appimage or --rpm must be specified." >&2
+if [[ "$DO_TARBALL" == "false" && "$DO_DEB" == "false" && "$DO_RPM" == "false" && "$DO_APPIMAGE" == "false" && "$DO_ARCH" == "false" ]]; then
+    echo "Error: At least one of --tarball, --deb, --appimage, --arch or --rpm must be specified." >&2
     help_info
     exit 1
 fi
@@ -108,6 +114,11 @@ if [ "${DO_APPIMAGE}" == "true" ]; then
         echo "Error: pkg2appimage not found. Set PKG2APPIMAGE_PATH or install pkg2appimage from here: https://github.com/AppImageCommunity/pkg2appimage" >&2
         exit 1
     fi
+fi
+
+# Check if on Arch Linux
+if ! grep -q "Arch Linux" /etc/os-release; then
+    echo "Building an Arch package will only work on Arch Linux" && exit 1
 fi
 
 export GRAM_BUNDLE=true
@@ -146,8 +157,8 @@ fi
 script/generate-licenses
 
 if command -v clang &>/dev/null; then
-  CC=${CC:+$(which clang)}
-  export CC
+    CC=${CC:+$(which clang)}
+    export CC
 fi
 
 if [ "$DO_BUILD" = "true" ]; then
@@ -157,11 +168,11 @@ if [ "$DO_BUILD" = "true" ]; then
     # Build remote_server separately to prevent feature unification from other crates
     # from influencing dynamic libraries required by it.
     if [[ "$remote_server_triple" == "$musl_triple" ]]; then
-      RUSTFLAGS="${RUSTFLAGS:-} -C target-feature=+crt-static"
-      if command -v mold &> /dev/null; then
-        RUSTFLAGS="${RUSTFLAGS} -C linker=clang -C link-arg=-fuse-ld=mold"
-      fi
-      export RUSTFLAGS
+        RUSTFLAGS="${RUSTFLAGS:-} -C target-feature=+crt-static"
+        if command -v mold &>/dev/null; then
+            RUSTFLAGS="${RUSTFLAGS} -C linker=clang -C link-arg=-fuse-ld=mold"
+        fi
+        export RUSTFLAGS
     fi
     if [ "$BUILD_REMOTE" = "true" ]; then
         cargo build --release --target "${remote_server_triple}" --package remote_server
@@ -194,10 +205,10 @@ fi
 
 # Strip debug symbols (keeps symbol table for backtraces)
 if [ -f "${target_dir}/${target_triple}/release/gram" ]; then
-  objcopy --strip-debug "${target_dir}/${target_triple}/release/gram"
+    objcopy --strip-debug "${target_dir}/${target_triple}/release/gram"
 fi
 if [ -f "${target_dir}/${target_triple}/release/cli" ]; then
-  objcopy --strip-debug "${target_dir}/${target_triple}/release/cli"
+    objcopy --strip-debug "${target_dir}/${target_triple}/release/cli"
 fi
 if [ -f "${target_dir}/${remote_server_triple}/release/remote_server" ]; then
     objcopy --strip-debug "${target_dir}/${remote_server_triple}/release/remote_server"
@@ -258,4 +269,13 @@ fi
 if [ "$DO_RPM" = "true" ]; then
     envsubst <"crates/gram/resources/gram.desktop.in" >"crates/gram/resources/gram.desktop"
     cargo generate-rpm -p crates/gram --target-dir "${target_dir}/${target_triple}" --payload-compress "${GRAM_RPM_COMPRESSION:=zstd}"
+fi
+
+# Bundle Arch package
+if [ "$DO_ARCH" = "true" ]; then
+    envsubst "$RELEASE_VERSION" <"crates/gram/resources/arch/PKGBUILD.in" >"crates/gram/resources/arch/PKGBUILD"
+    updpkgsums crates/gram/resources/arch/PKGBUILD
+    makepkg -sc -D crates/gram/resources/arch
+    mkdir -p "${target_dir}/${target_triple}"/arch
+    cp crates/gram/resources/arch/gram-bin*pkg.tar.zst "${target_dir}/${target_triple}"/arch
 fi
