chore: fix lints and small bugs in shell scripts

diff --git a/script/bundle-freebsd b/script/bundle-freebsd
--- a/script/bundle-freebsd
+++ b/script/bundle-freebsd
@@ -20,6 +20,11 @@ while getopts 'h' flag; do
         help_info
         exit 0
         ;;
+    *)
+        echo "Error: Unexpected argument: $1" >&2
+        help_info
+        exit 1
+        ;;
     esac
 done
 
@@ -154,4 +159,4 @@ arch=$(uname -m)
 # tar -czvf "${target_dir}/release/$archive" -C ${temp_dir} "gram$suffix.app"
 
 gzip -f --stdout --best "${target_dir}/${remote_server_triple}/release/remote_server" \
-    > "${target_dir}/gram-remote-server-freebsd-x86_64.gz"
+    >"${target_dir}/gram-remote-server-freebsd-x86_64.gz"
diff --git a/script/bundle-linux b/script/bundle-linux
--- a/script/bundle-linux
+++ b/script/bundle-linux
@@ -1,9 +1,10 @@
 #!/usr/bin/env bash
 
 set -euxo pipefail
+shopt -s extglob
 
 help_info() {
-  echo "
+    echo "
 Usage: ${0##*/} [options]
 Build Linux packages for Gram.
 
@@ -12,7 +13,7 @@ At least one of --tarball, --deb, or --rpm must be specified.
 Options:
   -h, --help          Display this help and exit.
   --no-build          Skip building binaries (assume they're already built).
-  --no-build-remote   Skip building the `remote_server` binary
+  --no-build-remote   Skip building the remote_server binary
   --flatpak           Set GRAM_BUNDLE_TYPE=flatpak so that this can be included in system info.
   --tarball           Build a release .tar.gz archive.
   --deb               Build a .deb package.
@@ -30,53 +31,54 @@ DO_RPM=false
 
 while [[ $# -gt 0 ]]; do
     case $1 in
-        -h|--help)
-            help_info
-            exit 0
-            ;;
-        --flatpak)
-            export GRAM_BUNDLE_TYPE=flatpak
-            shift
-            ;;
-        --appimage)
-            export DO_APPIMAGE=true
-            export DO_DEB=true
-            shift
-            ;;
-        --no-build)
-            DO_BUILD=false
-            shift
-            ;;
-        --no-build-remote)
-            BUILD_REMOTE=false
-            shift
-            ;;
-        --tarball)
-            DO_TARBALL=true
-            shift
-            ;;
-        --deb)
-            DO_DEB=true
-            shift
-            ;;
-        --rpm)
-            DO_RPM=true
-            shift
-            ;;
-        --)
-            shift
-            break
-            ;;
-        -*)
-            echo "Unknown option: $1" >&2
-            help_info
-            exit 1
-            ;;
-        *)
-            echo "Error: Unexpected argument: $1" >&2
-            help_info
-            exit 1
-            ;;
+    -h | --help)
+        help_info
+        exit 0
+        ;;
+    --flatpak)
+        export GRAM_BUNDLE_TYPE=flatpak
+        shift
+        ;;
+    --appimage)
+        export DO_APPIMAGE=true
+        export DO_DEB=true
+        shift
+        ;;
+    --no-build)
+        DO_BUILD=false
+        BUILD_REMOTE=false
+        shift
+        ;;
+    --no-build-remote)
+        BUILD_REMOTE=false
+        shift
+        ;;
+    --tarball)
+        DO_TARBALL=true
+        shift
+        ;;
+    --deb)
+        DO_DEB=true
+        shift
+        ;;
+    --rpm)
+        DO_RPM=true
+        shift
+        ;;
+    --)
+        shift
+        break
+        ;;
+    -*)
+        echo "Unknown option: $1" >&2
+        help_info
+        exit 1
+        ;;
+    *)
+        echo "Error: Unexpected argument: $1" >&2
+        help_info
+        exit 1
+        ;;
     esac
 done
 
@@ -89,17 +91,18 @@ fi
 
 # Check if cargo-deb is installed
 if [ "${DO_DEB}" == "true" ]; then
-    cargo deb --help > /dev/null 2>&1 || (echo "cargo-deb is not installed" && exit 1)
+    cargo deb --help >/dev/null 2>&1 || (echo "cargo-deb is not installed" && exit 1)
 fi
 
 # Check if cargo-generate-rpm is installed
 if [ "${DO_RPM}" == "true" ]; then
-    cargo generate-rpm --help > /dev/null 2>&1 || (echo "cargo-generate-rpm is not installed" && exit 1)
+    cargo generate-rpm --help >/dev/null 2>&1 || (echo "cargo-generate-rpm is not installed" && exit 1)
 fi
 
 # Check if pkg2appimage (https://github.com/AppImageCommunity/pkg2appimage) is installed
 if [ "${DO_APPIMAGE}" == "true" ]; then
-    export gram_dir=$(pwd)
+    gram_dir=$(pwd)
+    export gram_dir
     PKG2APPIMAGE_CMD="${PKG2APPIMAGE_PATH:-$(command -v pkg2appimage || true)}"
     if [ -z "${PKG2APPIMAGE_CMD}" ]; then
         echo "Error: pkg2appimage not found. Set PKG2APPIMAGE_PATH or install pkg2appimage from here: https://github.com/AppImageCommunity/pkg2appimage" >&2
@@ -117,7 +120,8 @@ currentversion="$(gcc -dumpversion)"
 requiredversion="14"
 version_info=$(rustc --version --verbose)
 host_line=$(echo "$version_info" | grep host)
-export target_triple=${host_line#*: }
+target_triple=${host_line#*: }
+export target_triple
 if [ "$(printf '%s\n' "$requiredversion" "$currentversion" | sort -V | head -n1)" = "$requiredversion" ]; then
     echo "Handle GCC version 14+ when compiling remote server..."
     export AWS_LC_SYS_CC=clang
@@ -128,7 +132,8 @@ channel=$(<crates/gram/RELEASE_CHANNEL)
 target_dir="${CARGO_TARGET_DIR:-target}"
 
 version="$(script/get-crate-version gram)"
-export RELEASE_VERSION="${version}"
+RELEASE_VERSION="${version}"
+export RELEASE_VERSION
 
 musl_triple=${target_triple%-gnu}-musl
 remote_server_triple=${REMOTE_SERVER_TARGET:-"${musl_triple}"}
@@ -140,15 +145,18 @@ fi
 # Generate the licenses first, so they can be baked into the binaries
 script/generate-licenses
 
-export CC=$(which clang)
+CC=$(which clang)
+export CC
 
 if [ "$DO_BUILD" = "true" ]; then
-    export RUSTFLAGS="${RUSTFLAGS:-} -C link-args=-Wl,--disable-new-dtags,-rpath,\$ORIGIN/../lib"
+    RUSTFLAGS="${RUSTFLAGS:-} -C link-args=-Wl,--disable-new-dtags,-rpath,\$ORIGIN/../lib"
+    export RUSTFLAGS
     cargo build --release --target "${target_triple}" --package gram --package cli
     # Build remote_server separately to prevent feature unification from other crates
     # from influencing dynamic libraries required by it.
     if [[ "$remote_server_triple" == "$musl_triple" ]]; then
-        export RUSTFLAGS="${RUSTFLAGS:-} -C target-feature=+crt-static"
+        RUSTFLAGS="${RUSTFLAGS:-} -C target-feature=+crt-static"
+        export RUSTFLAGS
     fi
     if [ "$BUILD_REMOTE" = "true" ]; then
         cargo build --release --target "${remote_server_triple}" --package remote_server
@@ -196,10 +204,10 @@ if [ "$DO_TARBALL" = "true" ]; then
     cp "${target_dir}/${target_triple}/release/cli" "${gram_dir}/bin/gram"
 
     mkdir -p "${gram_dir}/lib"
-    ldd "${target_dir}/${target_triple}/release/gram" \
-        | cut -d' ' -f3 \
-        | grep -v '\<\(libstdc++.so\|libc.so\|libgcc_s.so\|libm.so\|libpthread.so\|libdl.so\)' \
-        | xargs -I{} cp {} "${gram_dir}/lib/"
+    ldd "${target_dir}/${target_triple}/release/gram" |
+        cut -d' ' -f3 |
+        grep -v '\<\(libstdc++.so\|libc.so\|libgcc_s.so\|libm.so\|libpthread.so\|libdl.so\)' |
+        xargs -I{} cp {} "${gram_dir}/lib/"
 
     mkdir -p "${gram_dir}/share/icons/hicolor/512x512/apps"
     cp "crates/gram/resources/app-icon${suffix}.png" "${gram_dir}/share/icons/hicolor/512x512/apps/gram.png"
@@ -207,39 +215,38 @@ if [ "$DO_TARBALL" = "true" ]; then
     cp "crates/gram/resources/app-icon${suffix}@2x.png" "${gram_dir}/share/icons/hicolor/1024x1024/apps/gram.png"
 
     mkdir -p "${gram_dir}/share/applications"
-    envsubst < "crates/gram/resources/gram.desktop.in" > "${gram_dir}/share/applications/gram${suffix}.desktop"
+    envsubst <"crates/gram/resources/gram.desktop.in" >"${gram_dir}/share/applications/gram${suffix}.desktop"
     chmod +x "${gram_dir}/share/applications/gram${suffix}.desktop"
 
     cp "assets/licenses.md" "${gram_dir}/licenses.md"
 
     archive="gram-linux-${arch}.tar.gz"
-    remove_match="gram(-[a-zA-Z0-9]+)?-linux-$(uname -m)\.tar\.gz"
-    ls "${target_dir}/release" | grep -E "${remove_match}" | xargs -d "\n" -I {} rm -f "${target_dir}/release/{}" || true
+    rm -f "${target_dir}"/release/gram?(+([-[:alnum:]]))-linux-"$(uname -m)".tar.gz
     tar -czvf "${target_dir}/release/${archive}" -C "${temp_dir}" "gram${suffix}.app"
 
     if [ "$BUILD_REMOTE" = "true" ]; then
         gzip -f --stdout --best "${target_dir}/${remote_server_triple}/release/remote_server" \
-            > "${target_dir}/gram-remote-server-linux-${arch}.gz"
+            >"${target_dir}/gram-remote-server-linux-${arch}.gz"
     fi
 fi
 
 # Bundle .deb package
 if [ "$DO_DEB" = "true" ]; then
-    envsubst < "crates/gram/resources/gram.desktop.in" > "crates/gram/resources/gram.desktop"
+    envsubst <"crates/gram/resources/gram.desktop.in" >"crates/gram/resources/gram.desktop"
     CARGO_TARGET_DIR="${target_dir}/${target_triple}" cargo deb -p gram --no-build --compress-type xz
 
     # Bundle AppImage from .deb package
     if [ "$DO_APPIMAGE" = "true" ]; then
-        envsubst < "crates/gram/resources/appimage/recipe.yaml.in" > "/tmp/recipe.yaml"
+        envsubst <"crates/gram/resources/appimage/recipe.yaml.in" >"/tmp/recipe.yaml"
         $PKG2APPIMAGE_CMD "/tmp/recipe.yaml"
-        mkdir -p target/${target_triple}/AppImage
-        mv out/Gram*.AppImage -t target/${target_triple}/AppImage/
+        mkdir -p "target/${target_triple}/AppImage"
+        mv out/Gram*.AppImage -t "target/${target_triple}/AppImage/"
         rm -r out gram
     fi
 fi
 
 # Bundle .rpm package
 if [ "$DO_RPM" = "true" ]; then
-    envsubst < "crates/gram/resources/gram.desktop.in" > "crates/gram/resources/gram.desktop"
+    envsubst <"crates/gram/resources/gram.desktop.in" >"crates/gram/resources/gram.desktop"
     cargo generate-rpm -p crates/gram --target-dir "${target_dir}/${target_triple}" --payload-compress zstd
 fi
diff --git a/script/bundle-mac b/script/bundle-mac
--- a/script/bundle-mac
+++ b/script/bundle-mac
@@ -25,16 +25,16 @@ can_code_sign=false
 # the signing key using:
 # security find-identity -p codesigning
 if [[ -f ~/.local.secrets ]]; then
-  . ~/.local.secrets
-  export APPLE_ID
-  export APPLE_PASSWORD_GRAM
-  export APPLE_TEAM_ID
-  export APPLE_SIGNING_KEY
+    . "$HOME/.local.secrets"
+    export APPLE_ID
+    export APPLE_PASSWORD_GRAM
+    export APPLE_TEAM_ID
+    export APPLE_SIGNING_KEY
 fi
 
 # Function for displaying help info
 help_info() {
-  echo "
+    echo "
 Usage: ${0##*/} [options] [architecture=host]
 Build the application bundle for macOS.
 
@@ -46,27 +46,30 @@ Options:
   "
 }
 
-while getopts 'bdloih' flag
-do
+while getopts 'bdloih' flag; do
     case "${flag}" in
-        b) do_build=false;;
-        o) open_result=true;;
-        d)
-            export CARGO_INCREMENTAL=true
-            export CARGO_BUNDLE_SKIP_BUILD=true
-            build_flag="";
-            target_dir="debug"
-            ;;
-        i) local_install=true;;
-        h)
-           help_info
-           exit 0
-           ;;
+    b) do_build=false ;;
+    o) open_result=true ;;
+    d)
+        export CARGO_INCREMENTAL=true
+        export CARGO_BUNDLE_SKIP_BUILD=true
+        build_flag=""
+        target_dir="debug"
+        ;;
+    i) local_install=true ;;
+    h)
+        help_info
+        exit 0
+        ;;
+    *)
+        echo "Error: Unexpected argument: $1" >&2
+        help_info
+        exit 1
+        ;;
     esac
 done
 
-shift $((OPTIND-1))
-
+shift $((OPTIND - 1))
 
 # Get release channel
 pushd crates/gram
@@ -79,7 +82,7 @@ export GRAM_BUNDLE=true
 cargo_bundle_version=$(cargo -q bundle --help 2>&1 | head -n 1 || echo "")
 
 if [[ "$do_build" = "true" ]]; then
-  cargo install cargo-bundle --git https://github.com/zed-industries/cargo-bundle.git --branch zed-deploy
+    cargo install cargo-bundle --git https://github.com/zed-industries/cargo-bundle.git --branch zed-deploy
 fi
 
 # Deal with versions of macOS that don't include libstdc++ headers
@@ -104,17 +107,17 @@ fi
 
 if [[ "$do_build" = "true" ]]; then
 
-  # Generate the licenses first, so they can be baked into the binaries
-  script/generate-licenses
+    # Generate the licenses first, so they can be baked into the binaries
+    script/generate-licenses
 
-  rustup target add $target_triple
+    rustup target add "$target_triple"
 
-  echo "Compiling gram binaries"
-  cargo build ${build_flag} --package gram --package cli --target $target_triple
-  # Build remote_server in separate invocation to prevent feature unification from other crates
-  # from influencing dynamic libraries required by it.
-  echo "Compiling remote_server for $target_triple"
-  cargo build ${build_flag} --package remote_server --target $target_triple
+    echo "Compiling gram binaries"
+    cargo build ${build_flag} --package gram --package cli --target "$target_triple"
+    # Build remote_server in separate invocation to prevent feature unification from other crates
+    # from influencing dynamic libraries required by it.
+    echo "Compiling remote_server for $target_triple"
+    cargo build ${build_flag} --package remote_server --target "$target_triple"
 
 fi
 
@@ -126,7 +129,7 @@ sed \
     "s/package.metadata.bundle-${channel}/package.metadata.bundle/" \
     Cargo.toml
 
-app_path=$(cargo bundle ${build_flag} --target $target_triple --select-workspace-root | xargs)
+app_path=$(cargo bundle ${build_flag} --target "$target_triple" --select-workspace-root | xargs)
 
 mv Cargo.toml.backup Cargo.toml
 popd
@@ -146,12 +149,12 @@ function download_and_unpack() {
 
     temp_dir=$(mktemp -d)
 
-    if ! command -v curl &> /dev/null; then
+    if ! command -v curl &>/dev/null; then
         echo "curl is not installed. Please install curl to continue."
         exit 1
     fi
 
-    curl --silent --fail --location "$url" | tar -xvz -C "$temp_dir" -f - $path_to_unpack
+    curl --silent --fail --location "$url" | tar -xvz -C "$temp_dir" -f - "$path_to_unpack"
 
     mv "$temp_dir/$path_to_unpack" "$target_path"
 
@@ -166,16 +169,16 @@ function download_git() {
     pushd "$tmp_dir"
 
     case "$architecture" in
-        aarch64-apple-darwin)
-            download_and_unpack "https://github.com/desktop/dugite-native/releases/download/${GIT_VERSION}/dugite-native-${GIT_VERSION}-${GIT_VERSION_SHA}-macOS-arm64.tar.gz" bin/git ./git
-            ;;
-        x86_64-apple-darwin)
-            download_and_unpack "https://github.com/desktop/dugite-native/releases/download/${GIT_VERSION}/dugite-native-${GIT_VERSION}-${GIT_VERSION_SHA}-macOS-x64.tar.gz" bin/git ./git
-            ;;
-        *)
-            echo "Unsupported architecture: $architecture"
-            exit 1
-            ;;
+    aarch64-apple-darwin)
+        download_and_unpack "https://github.com/desktop/dugite-native/releases/download/${GIT_VERSION}/dugite-native-${GIT_VERSION}-${GIT_VERSION_SHA}-macOS-arm64.tar.gz" bin/git ./git
+        ;;
+    x86_64-apple-darwin)
+        download_and_unpack "https://github.com/desktop/dugite-native/releases/download/${GIT_VERSION}/dugite-native-${GIT_VERSION}-${GIT_VERSION_SHA}-macOS-x64.tar.gz" bin/git ./git
+        ;;
+    *)
+        echo "Unsupported architecture: $architecture"
+        exit 1
+        ;;
     esac
 
     popd
@@ -191,7 +194,7 @@ function sign_app_binaries() {
     echo "Downloading git binary"
     download_git "${target_triple}" "${app_path}/Contents/MacOS/git"
 
-    cp crates/gram/contents/$channel/embedded.provisionprofile "${app_path}/Contents/"
+    cp crates/gram/contents/"$channel"/embedded.provisionprofile "${app_path}/Contents/"
 
     if [[ $can_code_sign = true ]]; then
         echo "Code signing binaries"
@@ -212,9 +215,9 @@ function sign_app_binaries() {
         # - create a PR and tag it with the `run-bundling` label, and download the .dmg file from there.
         # - create your own signing key, and update signing key references to your own team ID
         # then comment out this line.
-        cat crates/gram/resources/gram.entitlements | sed '/com.apple.developer.associated-domains/,+1d' > "${app_path}/Contents/Resources/gram.entitlements"
+        cat crates/gram/resources/gram.entitlements | sed '/com.apple.developer.associated-domains/,+1d' >"${app_path}/Contents/Resources/gram.entitlements"
 
-        codesign --force --deep --entitlements "${app_path}/Contents/Resources/gram.entitlements" --sign ${APPLE_SIGNING_KEY} "${app_path}" -v
+        codesign --force --deep --entitlements "${app_path}/Contents/Resources/gram.entitlements" --sign "${APPLE_SIGNING_KEY}" "${app_path}" -v
     fi
 
     bundle_name=$(basename "$app_path")
@@ -243,13 +246,13 @@ function sign_app_binaries() {
         dmg_file_path="${dmg_target_directory}/Gram-${arch_suffix}.dmg"
         xcode_bin_dir_path="$(xcode-select -p)/usr/bin"
 
-        rm -rf ${dmg_source_directory}
-        mkdir -p ${dmg_source_directory}
+        rm -rf "${dmg_source_directory}"
+        mkdir -p "${dmg_source_directory}"
         mv "${app_path}" "${dmg_source_directory}"
         notarization_key_file=$(mktemp)
 
         echo "Adding symlink to /Applications to ${dmg_source_directory}"
-        ln -s /Applications ${dmg_source_directory}
+        ln -s /Applications "${dmg_source_directory}"
 
         echo "Creating final DMG at ${dmg_file_path} using ${dmg_source_directory}"
         hdiutil create -volname Gram -srcfolder "${dmg_source_directory}" -ov -format UDZO "${dmg_file_path}"
@@ -257,7 +260,7 @@ function sign_app_binaries() {
         # If someone runs this bundle script locally, a symlink will be placed in `dmg_source_directory`.
         # This symlink causes CPU issues with Gram if the Gram codebase is the project being worked on, so we simply remove it for now.
         echo "Removing symlink to /Applications from ${dmg_source_directory}"
-        rm ${dmg_source_directory}/Applications
+        rm "${dmg_source_directory}"/Applications
 
         if [[ $can_code_sign = true ]]; then
             echo "Notarizing DMG with Apple"
@@ -267,7 +270,7 @@ function sign_app_binaries() {
         fi
 
         if [ "$open_result" = true ]; then
-            open $dmg_target_directory
+            open "$dmg_target_directory"
         fi
     fi
 }
@@ -281,8 +284,8 @@ function sign_binary() {
     fi
 }
 
-cp target/${target_triple}/${target_dir}/gram "${app_path}/Contents/MacOS/gram"
-cp target/${target_triple}/${target_dir}/cli "${app_path}/Contents/MacOS/cli"
+cp target/"${target_triple}"/${target_dir}/gram "${app_path}/Contents/MacOS/gram"
+cp target/"${target_triple}"/${target_dir}/cli "${app_path}/Contents/MacOS/cli"
 ./script/mac-icon-to-car
 cp -r target/Assets.car "${app_path}/Contents/Resources/Assets.car"
 plist_file="${app_path}/Contents/Info.plist"
@@ -293,4 +296,3 @@ sign_app_binaries
 
 sign_binary "target/$target_triple/release/remote_server"
 echo "target/gram-remote-server-macos-$arch_suffix"
-
